dataset:
  anno_dir: ./data
  img_dir: ./data/FACEREG
  img_size: [480, 640]
  augmentation:
    flip:
      prob: 0.5
    rotation:
      degrees: 10
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
model:
  embedding_size: 256
loss:
  margin: 1.0
optimizer:
  name: 'adam'
  lr: 0.000001
  weight_decay: 0.0001
scheduler:
  name: 'None'
train:
  batch_size: 8
  epoch: 30
  num_workers: 2
  save_path: './outputs'
inference:
  vector_database: './data/FACEREG_EMBEDDING'
  batch_size: 8
  num_workers: 2
  checkpoint: 'best_epoch_23.pth'