dataset:
    audio_dir: './data/VOICECOMMAND'
    sample_rate: 16000
    num_samples: 80000
    transformation:
        n_mfcc: 64
        n_fft: 1024
        hop_length: 512
        n_mels: 64
    augmentation:
        rate: 0.5
        random_vol:
            min_gain: 0.6
            max_gain: 1.0
        random_freq_mask:
            max_freq_mask_param: 10
        random_time_mask:
            max_time_mask_param: 10
        random_time_shift:
            max_shift: 4000
        add_white_noise:
            noise_level: 0.0001
model:
    d_model: 256
    num_layers: 18
    dropout: 0.1
    bidirectional: False
    d_out: 5
optimizer:
  name: 'adam'
  lr: 0.001
  weight_decay: 0.0001
scheduler:
  name: 'None'
train:
  batch_size: 8
  epoch: 3
  num_workers: 0
  save_path: './outputs'
inference:
  batch_size: 1
  num_workers: 0
  checkpoint: 'best_epoch.pth'